version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  transfers:
    build: .
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/ts-template
      MONGO_TRANSFERS_COLLECTION_NAME: transfers
      RABBIT_URI: amqp://rabbit
      SPIKE_ENABLED: true
      SHRAGA_ENABLED: true
    ports:
      - 8000:8000
